# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
  
  
  generate-version:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - uses: rmeneely/git-next-version@v1
        with:
          tag_pattern: '[0-9]*.[0-9]*.[0-9]*'
          auto_increment: 'true'
          auto_increment_major_version_pattern: 'major:|breaking:|incompatible:'
          auto_increment_minor_version_pattern: 'minor:|feature:'
          auto_increment_limit: 'patch'
          set_next_version_tag: 'true'
          
      - name: Tag Release
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ env.NEXT_VERSION }}
          message: "Releasing version ${{ env.NEXT_VERSION }}"
        
    outputs: 
      new-version: ${{ env.NEXT_VERSION }}
  
  publish:
    runs-on: ubuntu-latest
    needs: generate-version
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
        
      - name: Publish PrettyBots.Environment.Abstraction
        uses: rohith/publish-nuget@v2
        continue-on-error: true
        with:
          PROJECT_FILE_PATH: PrettyBots.Environment.Abstraction/PrettyBots.Environment.Abstraction.csproj
          VERSION_STATIC: ${{ needs.generate-version.outputs.new-version }}
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
          
      - name: Publish PrettyBots.Environment
        uses: rohith/publish-nuget@v2
        continue-on-error: true
        with:
          PROJECT_FILE_PATH: PrettyBots.Environment/PrettyBots.Environment.csproj
          VERSION_STATIC: ${{ needs.generate-version.outputs.new-version }}
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
          
      - name: Publish PrettyBots.Validators.Abstraction
        uses: rohith/publish-nuget@v2
        continue-on-error: true
        with:
          PROJECT_FILE_PATH: PrettyBots.Validators.Abstraction/PrettyBots.Validators.Abstraction.csproj
          VERSION_STATIC: ${{ needs.generate-version.outputs.new-version }}
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
          
      - name: Publish PrettyBots.Storages.Abstraction
        uses: rohith/publish-nuget@v2
        continue-on-error: true
        with:
          PROJECT_FILE_PATH: PrettyBots.Storages.Abstraction/PrettyBots.Storages.Abstraction.csproj
          VERSION_STATIC: ${{ needs.generate-version.outputs.new-version }}
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
          
      - name: Publish PrettyBots.Storages.Json
        uses: rohith/publish-nuget@v2
        continue-on-error: true
        with:
          PROJECT_FILE_PATH: PrettyBots.Storages.Json/PrettyBots.Storages.Json.csproj
          VERSION_STATIC: ${{ needs.generate-version.outputs.new-version }}
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
          
      - name: Publish PrettyBots.Storages.EFCore
        uses: rohith/publish-nuget@v2
        continue-on-error: true
        with:
          PROJECT_FILE_PATH: PrettyBots.Storages.EFCore/PrettyBots.Storages.EFCore.csproj
          VERSION_STATIC: ${{ needs.generate-version.outputs.new-version }}
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
          
      - name: Publish PrettyBots.Utilities
        uses: rohith/publish-nuget@v2
        continue-on-error: true
        with:
          PROJECT_FILE_PATH: PrettyBots.Utilities/PrettyBots.Utilities.csproj
          VERSION_STATIC: ${{ needs.generate-version.outputs.new-version }}
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
          
      - name: Publish PrettyBots.Interactions.Abstraction
        uses: rohith/publish-nuget@v2
        continue-on-error: true
        with:
          PROJECT_FILE_PATH: PrettyBots.Interactions.Abstraction/PrettyBots.Interactions.Abstraction.csproj
          VERSION_STATIC: ${{ needs.generate-version.outputs.new-version }}
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
          
      - name: Publish PrettyBots.Attributes
        uses: rohith/publish-nuget@v2
        continue-on-error: true
        with:
          PROJECT_FILE_PATH: PrettyBots.Attributes/PrettyBots.Attributes.csproj
          VERSION_STATIC: ${{ needs.generate-version.outputs.new-version }}
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
          
      - name: Publish PrettyBots.Validators
        uses: rohith/publish-nuget@v2
        continue-on-error: true
        with:
          PROJECT_FILE_PATH: PrettyBots.Validators/PrettyBots.Validators.csproj
          VERSION_STATIC: ${{ needs.generate-version.outputs.new-version }}
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
          
      - name: Publish PrettyBots.Interactions
        uses: rohith/publish-nuget@v2
        continue-on-error: true
        with:
          PROJECT_FILE_PATH: PrettyBots.Interactions/PrettyBots.Interactions.csproj
          VERSION_STATIC: ${{ needs.generate-version.outputs.new-version }}
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
          
      - name: Publish PrettyBots.Environment.Telegram
        uses: rohith/publish-nuget@v2
        continue-on-error: true
        with:
          PROJECT_FILE_PATH: PrettyBots.Environment.Telegram/PrettyBots.Environment.Telegram.csproj
          VERSION_STATIC: ${{ needs.generate-version.outputs.new-version }}
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
          
      - name: Publish PrettyBots.Interactions.Telegram
        uses: rohith/publish-nuget@v2
        continue-on-error: true
        with:
          PROJECT_FILE_PATH: PrettyBots.Interactions.Telegram/PrettyBots.Interactions.Telegram.csproj
          VERSION_STATIC: ${{ needs.generate-version.outputs.new-version }}
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}    
      
