# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
  
  
  generate-version:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - uses: rmeneely/git-next-version@v1
        with:
          tag_pattern: 'v[0-9]*.[0-9]*.[0-9]*'
          auto_increment: 'true'
          auto_increment_major_version_pattern: 'major:|breaking:|incompatible:'
          auto_increment_minor_version_pattern: 'minor:|feature:'
          auto_increment_limit: 'patch'
          remove_prefix: 'true'
          
      - name: Tag Release
        uses: rickstaa/action-create-tag@v1
        with:
          tag: v${{ env.NEXT_VERSION }}
          message: "Releasing version v${{ env.NEXT_VERSION }}"
        
    outputs: 
      new-version: ${{ env.NEXT_VERSION }}
  
  publish:
    runs-on: ubuntu-latest
    needs: generate-version
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x
          
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build NuGet packages
        run: |
          dotnet pack -c Release \
          -p:PackageVersion=${{ needs.generate-version.outputs.new-version }} \
          -o packages
    
      - name: Publish packages
        continue-on-error: true
        run: dotnet nuget push packages/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json